### PR TITLE
Merge `branch-23.02` into `branch-23.04`

### PR DESCRIPTION
**Pull request by ajschmidt8**
This PR fixes the merge conflicts in #1125 to enable the latest changes from `branch-23.02` to be merged into `branch-23.04`.

### CODE REVIEW

**Comment by ajschmidt8** [comment]
@wence-, #1125 shouldn't have been closed.

Due to our current branching strategy, we always forward hotfixes from the previous dev branch into the current dev branch (even if they need to be undone on the current dev branch).

We plan on making changes to the branching strategy in the future, but for now this is the status quo.

I'm also eager to see if this pin fixes the CI issues that have cropped up in unrelated PRs like #1120.

**Review by raydouglass — APPROVED** [review]

**Comment by wence-** [comment]
> @wence-, #1125 shouldn't have been closed.

Ah, sorry!
 
> Due to our current branching strategy, we always forward hotfixes from the previous dev branch into the current dev branch (even if they need to be undone on the current dev branch).

Thanks, makes sense.

> We plan on making changes to the branching strategy in the future, but for now this is the status quo.
> 
> I'm also eager to see if this pin fixes the CI issues that have cropped up in unrelated PRs like #1120.

**Comment by wence-** [comment]
> I'm also eager to see if this pin fixes the CI issues that have cropped up in unrelated PRs like #1120.

I think it would (if the failures were due to nvml issues), but we should probably unpin again given that trunk ostensibly has a more compatible fix.

**Comment by wence-** [comment]
> > I'm also eager to see if this pin fixes the CI issues that have cropped up in unrelated PRs like #1120.
> 
> I think it would (if the failures were due to nvml issues), but we should probably unpin again given that trunk ostensibly has a more compatible fix.

Did that here https://github.com/rapidsai/dask-cuda/pull/1130

**Pull request merged**
