### PR TITLE
Ensure tests run for Python `3.10`

### PR DESCRIPTION
**Pull request by ajschmidt8**
Previously we had disabled `cucim` testing for Python `3.10` because the tests depended on `3.10` packages of `cudf`, which weren't previously available.

Now that `3.10` packages of `cudf` are available, we can enable `3.10` testing for `cucim`.

### CODE REVIEW

**Review by Ethyling — APPROVED** [review]

**Comment by charlesbluca** [comment]
It looks like this is failing because there aren't 3.10 builds of `cucim` available yet:

```
Encountered problems while solving:
  - package cucim-23.02.00a221226-cuda_11_py39_gc06355c_37 requires python_abi 3.9.* *_cp39, but 
```

**Comment by ajschmidt8** [comment]
> It looks like this is failing because there aren't 3.10 builds of `cucim` available yet:

I will open that PR now.

**Comment by ajschmidt8** [comment]
https://github.com/rapidsai/cucim/pull/476

**Comment by ajschmidt8** [comment]
This PR needs https://github.com/rapidsai/cucim/pull/480 published before it will pass.

**Comment by ajschmidt8** [comment]
this PR needs https://github.com/rapidsai/dask-cuda/pull/1086 to fix the current CI failures.

**Pull request merged**
