### PR TITLE
Use `has_cuda_context` from Distributed

### PR DESCRIPTION
**Pull request by pentschev**
Waiting for the next Distributed release for this, since building conda packages fails otherwise.

### CODE REVIEW

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
rerun tests

**Comment by pentschev** [comment]
Thanks for working on the release @jakirkham , this is now passing and we can merge! Thanks @quasiben for the review too.

**Comment by pentschev** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Also have PR ( https://github.com/rapidsai/integration/pull/354 ) up to bump the RAPIDS Dask + Distributed requirements. If you have a moment to look at it, that would be appreciated 🙂

**Pull request merged**
