### PR TITLE
Fixed `ProxyObject.__del__` to use the new Disk IO API from #791

### PR DESCRIPTION
**Pull request by madsbk**
Anyone that knows how to make a `pytest` that tests exceptions in class destructors?

### CODE REVIEW

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
> Anyone that knows how to make a `pytest` that tests exceptions in class destructors?

@madsbk what exactly do you want to test? You want to ensure no exceptions are raised in the destructor, or do you want to verify that the exception is indeed raised? If it's the latter, during `__del__` no exceptions should be raised and thus there's a design issue.

**Comment by madsbk** [comment]
This: `You want to ensure no exceptions are raised in the destructor`.
I have tried with the `capsys` and `capfd` fixtures but it doesn't work.

It is not blocking this PR but it would be nice to have a regression test

**Comment by pentschev** [comment]
@madsbk we can add `error::pytest.PytestUnraisableExceptionWarning` to https://github.com/rapidsai/dask-cuda/blob/branch-21.12/pytest.ini , that will error on uncatched exceptions in `__del__`.

**Review by pentschev — APPROVED** [review]
LGTM @madsbk . It's up to you whether you want to add `error::pytest.PytestUnraisableExceptionWarning`, or maybe even `error::pytest.PytestWarning`. I think it wouldn't hurt for us to be more strict on pytest warnings.

**Comment by madsbk** [comment]
> LGTM @madsbk . It's up to you whether you want to add `error::pytest.PytestUnraisableExceptionWarning`, or maybe even `error::pytest.PytestWarning`. I think it wouldn't hurt for us to be more strict on pytest warnings.

Thanks @pentschev, let's merge this PR and then try a more strict warning policy in another PR.

**Comment by madsbk** [comment]
@gpucibot merge

**Pull request merged**
