### PR TITLE
Remove explicit UCX config from tests

### PR DESCRIPTION
**Pull request by pentschev**
Rely on UCX defaults for selection of transport in tests, which is now the preferred way to launch setup a cluster.

### CODE REVIEW

**Comment by quasiben** [comment]
Woohoo!

**Comment by quasiben** [comment]
rerun tests

**Comment by pentschev** [comment]
Some of the failing tests are being resolved by https://github.com/rapidsai/dask-cuda/pull/1200, the remaining are being resolved by https://github.com/rapidsai/dask-cuda/pull/1199/commits/93108616b5c11f8ffcc9fc89f5eaefae6ce183c2 .

**Pull request merged**
