### PR TITLE
Fix CUDA_VISIBLE_DEVICES tests

### PR DESCRIPTION
**Pull request by pentschev**
After recent changes in Distributed, particularly https://github.com/dask/distributed/pull/4866, worker processes will now attempt to get information from PyNVML based on the index specified in `CUDA_VISIBLE_DEVICES`. Some of our tests purposely test device numbers that may not exist in some systems (e.g., gpuCI where only single-GPU is supported) to ensure the `CUDA_VISIBLE_DEVICES` of each worker indeed respects the ordering of `dask_cuda.utils.cuda_visible_devices`. The changes here introduce a new `MockWorker` class that will monkey-patch the behavior of NVML usage of `distributed.Worker`, which can then be used to return those tests to a working state.

### CODE REVIEW

**Comment by pentschev** [comment]
Failures are unrelated: https://github.com/rapidsai/dask-cuda/pull/637#issuecomment-854169628, probably still needs https://github.com/rapidsai/cudf/pull/8426 to be in.

**Comment by galipremsagar** [comment]
rerun tests

**Comment by quasiben** [comment]
rerun tests

**Comment by quasiben** [comment]
I retargeted this PR to 21.08

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
> I retargeted this PR to 21.08

Why? If we're pinning today's Dask release for 21.06, then we need this in.

**Comment by pentschev** [comment]
I forgot this requires https://github.com/dask/distributed/pull/4873, CI won't pass until that's merged.

**Comment by jrbourbeau** [comment]
https://github.com/dask/distributed/pull/4873 is in now

**Comment by pentschev** [comment]
Thanks @jrbourbeau , rerunning!

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
I'm still trying to reproduce this, I attempted doing so also running the Local CI scripts, but all tests pass then as well on a DGX-1. I think the issue may be due to gpuCI having only a single GPU, I'll try that on a machine with only one GPU.

**Review by quasiben — APPROVED** [review]

**Comment by quasiben** [comment]
@gpucibot merge

**Comment by pentschev** [comment]
Thanks @quasiben !

**Pull request merged**
