### PR TITLE
Decrease data size to shorten spilling tests time

### PR DESCRIPTION
**Pull request by pentschev**
These tests generally take a lot of time, I think it's safe to reduce their sizes so that dask-cuda CI runs faster. Spilling tests alone used to take 228 seconds and take 72 seconds after this PR.

### CODE REVIEW

**Comment by pentschev** [comment]
I've been seeing explicit-comms tests being very unstable for the last month or so. I'm not exactly sure how we should deal with that, any ideas @madsbk @rjzamora ? One alternative is just to xfail them for now, but that may cover some actual issues down the road.

**Comment by rjzamora** [comment]
> I've been seeing explicit-comms tests being very unstable for the last month or so. I'm not exactly sure how we should deal with that, any ideas @madsbk @rjzamora ? One alternative is just to xfail them for now, but that may cover some actual issues down the road.

What kind of instabilities are you seeing?  xfailing these tests could be fine, since explicit comms are rarely used in practice.  However, we may just be ignoring a real problem that is merely being exposed by those tests (although it seems just as likely that something in explicit comms could be the root problem).

**Comment by madsbk** [comment]
I am fine with xfailing the tests as well. Do we have an issue tracking the CI failure?

**Comment by pentschev** [comment]
Sorry @rjzamora @madsbk , I should have filed an issue for that before, I did it now in https://github.com/rapidsai/dask-cuda/issues/431 . For the time being, I will xfail those tests just to unblock builds.

**Comment by pentschev** [comment]
rerun tests

**Review by quasiben — APPROVED** [review]
Merge when Green

**Comment by pentschev** [comment]
Thanks @quasiben , I guess your merge won't work as codecov failed, I'm going ahead and merging this.

**Pull request merged**
