### PR TITLE
Added installation info and example to the README

### PR DESCRIPTION
**Pull request by madsbk**

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by pentschev** [comment]
CuPy 6.0.0 is expected to be released this Thursday, May 16th. I suggest we wait, then update the README to reflect that and merge.

Otherwise, LGTM.

**Comment by mrocklin** [comment]
Thanks for doing this @madsbk 

One concern I have is the focus on CuPy here.  CuPy isn't a dependency of dask-cuda, or even a primary focus. People will use this library with other packages like cudf, torch, tensorflow and so on. I don't think that we should provide special support to CuPy in this project's readme.

Most people using dask-cuda today are probably people associated with RAPIDS development, particularly around cudf.

**Comment by pentschev** [comment]
That's a good point @mrocklin. If there are no objections, I think we could restructure the document a bit, keeping the CuPy instructions, and over time include examples for the various libraries that are supported (along with requirements to run those).

**Comment by mrocklin** [comment]
I agree that instructions like that should exist somewhere.  I'm not sure if here is the correct place.  I can't immediately think of a better place though.

**Comment by pentschev** [comment]
What if we move the instructions out of `README.md` into a different file in this repository?

**Comment by mrocklin** [comment]
That could make sense.  I think that we still need to figure out what is in-scope for this repository.  Originally it was just around improving the ability to set up Dask with CUDA GPUs.  It sounds like now we're considering it as a home for documentation on how to use Dask with GPU enabled libraries, which is new.

Some other options:

-  Somewhere within the RAPIDS documentation
-  Get things to a more stable state (like how you suggested to wait for cupy 6 and maybe maybe finish up the meta PR) and then add it to the standard Dask documentation
-  ...

**Comment by pentschev** [comment]
I think it's helpful to have this information rather sooner than later, independent of where. On the original discussion we had with @jakirkham we decided to create a gist where we could point people to. That would be fine to me as well until we are on a more stable state.

I don't know where would be (or if there is) an appropriate place for this documentation within RAPIDS outside of this repo.

**Comment by jakirkham** [comment]
FWIW moving the CuPy stuff to a gist still seems reasonable to me 🙂

**Comment by kkraus14** [comment]
add to whitelist

**Pull request closed without merging**
