### PR TITLE
Package license file

### PR DESCRIPTION
**Pull request by jakirkham**
Make sure the license file gets packaged in `sdist`s and `whl`s.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @ocefpaf (for vis)

**Comment by jakirkham** [comment]
rerun tests

**Review by pentschev — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Comment by madsbk** [comment]
rerun tests

**Comment by jakirkham** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Thanks all! 😄

**Pull request merged**
