### PR TITLE
[DO NOT MERGE] temporarily bump build stack to 9.3.0 for testing

### PR DESCRIPTION
**Pull request by kkraus14**
DO NOT MERGE

Testing for rapidsai/integration#202

### CODE REVIEW

**Comment by jakirkham** [comment]
FWIW this is pure Python. So wouldn't expect the compiler to matter much here.

**Comment by kkraus14** [comment]
> FWIW this is pure Python. So wouldn't expect the compiler to matter much here.

Just wanted to make sure we weren't causing solving issues mainly 😄

**Comment by jakirkham** [comment]
Ofc thanks for checking 🙂

There may be UCX issues cropping up, but those are unrelated

**Comment by mike-wendt** [comment]
Closing now that rapidsai/integration#202 is merged

**Pull request closed without merging**
