### PR TITLE
Replace weight by safe_sizeof

### PR DESCRIPTION
**Pull request by pentschev**
Fix for changes in https://github.com/dask/distributed/pull/4651

### CODE REVIEW

**Review by quasiben — APPROVED** [review]

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
It seems that there are other issues in Distributed: https://github.com/dask/distributed/commit/d5fc324bdef22f19d77c3d36e63a3778ceaac0b0#r49759517 . I'll retarget this to 0.20 and pin Distributed 2021.04.0 in 0.19 just as [dask-cudf does](https://github.com/rapidsai/cudf/blob/d501d2c0b9cc7309f08646a2677c019e6f7906b6/conda/recipes/dask-cudf/meta.yaml#L26-L27).

**Comment by jrbourbeau** [comment]
Thanks for tracking these issues down @pentschev. xref-ing https://github.com/dask/distributed/pull/4723 which adds `weight` back in to avoid any issues with `distributed` releasing before `dask-cuda`

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
@gpucibot merge

**Pull request merged**
