### PR TITLE
Update plugins to inherit from ``WorkerPlugin``

### PR DESCRIPTION
**Pull request by jrbourbeau**
Upstream in `distributed` we're considering enforcing plugins to inherit from their respective base class (e.g. `WorkerPlugin`, `SchedulerPlugin`, `NannyPlugin`) https://github.com/dask/distributed/pull/8149. This PR updates plugins here to inherhit from `WorkerPlugin`. This makes things a little more future-proof and is probably a good thing to do anyways.

### CODE REVIEW

**Comment by jrbourbeau** [comment]
cc @rjzamora @jacobtomlinson as this came up in a meeting earlier today

**Comment by jrbourbeau** [comment]
Btw, I'm not super familiar with the codebase here. So just let me know if there are other plugins around

**Review by pentschev — APPROVED** [review]
LGTM, thanks @jrbourbeau for helping us out with getting Dask-CUDA up-to-speed with latest Distributed changes!

**Pull request merged**
