### PR TITLE
[gpuCI] Auto-merge branch-0.7 to branch-0.8 [skip ci]

### PR DESCRIPTION
**Pull request by GPUtester**
Auto-merge triggered by push to `branch-0.7` that creates a PR to keep `branch-0.8` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

### CODE REVIEW

**Comment by GPUtester** [comment]
**FAILURE** - Unable to auto-merge due to conflicts. Manual merge necessary.

**Comment by kkraus14** [comment]
Do we need to resolve this before release...?

**Comment by mrocklin** [comment]
No, I think that this commit was made erroneously.  An equivalent commit is in 0.8

**Comment by pentschev** [comment]
Are we good to close this PR then? It looks like most (if not all changes) are in both branch-0.8 and branch-0.9.

**Comment by dillon-cullinan** [comment]
Closing this. Equivalent changes were made in 0.8 as separate commit hashes causing this to be unneeded.

**Pull request closed without merging**
