### PR TITLE
Unpin `dask` and `distributed` for `23.12` development

### PR DESCRIPTION
**Pull request by galipremsagar**
This PR relaxes `dask` and `distributed` versions pinning for `23.12` development.

xref: https://github.com/rapidsai/cudf/pull/14320

### CODE REVIEW

**Comment by pentschev** [comment]
@galipremsagar I pushed the changes from https://github.com/rapidsai/dask-cuda/pull/1256 into your branch, hope you don't mind.

**Comment by galipremsagar** [comment]
> @galipremsagar I pushed the changes from #1256 into your branch, hope you don't mind.

Absolutely fine by me. Thanks @pentschev !

**Review by jakirkham — APPROVED** [review]

**Review by pentschev — APPROVED** [review]

**Comment by galipremsagar** [comment]
@pentschev I think we have legit pytest failures this time, do we need to modify them?

**Comment by pentschev** [comment]
I'm looking at them now, will post here shortly.

**Comment by pentschev** [comment]
I'm xfailing the tests for now and filed https://github.com/rapidsai/dask-cuda/issues/1265 to investigate that.

**Comment by galipremsagar** [comment]
Thanks @pentschev !

**Comment by pentschev** [comment]
We've got some test failures due to AWS segfaults as we're still on PyArrow 12, rerunning those.

**Comment by pentschev** [comment]
This is being really hard here, `pr / conda-python-tests / tests (12.0.1, ubuntu22.04, amd64, 3.10, v100, latest)` failed 5 times with segfaults already:

```c++
[792bd23cf9a0:6818 :0:7196] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x10)
==== backtrace (tid:   7196) ====
 0  /opt/conda/envs/test/lib/python3.10/site-packages/ucp/_libs/../../../../libucs.so.0(ucs_handle_error+0x2fd) [0x7f1dff619fed]
 1  /opt/conda/envs/test/lib/python3.10/site-packages/ucp/_libs/../../../../libucs.so.0(+0x2a1e1) [0x7f1dff61a1e1]
 2  /opt/conda/envs/test/lib/python3.10/site-packages/ucp/_libs/../../../../libucs.so.0(+0x2a3aa) [0x7f1dff61a3aa]
 3  /usr/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f2080993520]
 4  /opt/conda/envs/test/lib/python3.10/site-packages/pyarrow/../../.././libaws-cpp-sdk-core.so(+0x824cc) [0x7f1e60d644cc]
 5  /opt/conda/envs/test/lib/python3.10/site-packages/pyarrow/../../../././libaws-c-io.so.1.0.0(+0x1c843) [0x7f1e60326843]
 6  /opt/conda/envs/test/lib/python3.10/site-packages/pyarrow/../../../././libaws-c-io.so.1.0.0(+0x167e6) [0x7f1e603207e6]
 7  /opt/conda/envs/test/lib/python3.10/site-packages/pyarrow/../../../././libaws-c-io.so.1.0.0(+0x16839) [0x7f1e60320839]
 8  /opt/conda/envs/test/lib/python3.10/site-packages/pyarrow/../../../././libaws-c-common.so.1(+0x26419) [0x7f1e604b3419]
 9  /usr/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f20809e5ac3]
10  /usr/lib/x86_64-linux-gnu/libc.so.6(clone+0x44) [0x7f2080a76bf4]
=================================
```

**Pull request merged**
