### PR TITLE
Update `test_worker_timeout`

### PR DESCRIPTION
**Pull request by pentschev**
`test_worker_timeout` is currently failing because the error message has changed, updating to match the new error message.

### CODE REVIEW

**Comment by pentschev** [comment]
See https://github.com/rapidsai/dask-cuda/actions/runs/5947335550/job/16129254824 for an example of the failure.

**Comment by quasiben** [comment]
rerun tests

**Review by quasiben — APPROVED** [review]

**Comment by pentschev** [comment]
Thanks @quasiben for the quick review/approval. Btw, `rerun tests` doesn't work anymore. You have to go to one of the tests and on the top right you'll see a `Re-run jobs` button where you can choose to rerun that failed jobs or all of them.

**Pull request merged**
