### PR TITLE
Fix whitespace & add URLs in `pyproject.toml`

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Review by pentschev — APPROVED** [review]
LGTM John. Are those just formatting fixes or do they get raised as errors and do not allow building in some specific scenario? In the latter case, should we look for a pre-commit hook to correctly parse that file?

**Comment by jakirkham** [comment]
No issues that I'm aware of. Just happened to spot them

**Comment by pentschev** [comment]
Thanks @jakirkham !

**Comment by jakirkham** [comment]
Thanks Peter! 🙏

**Pull request merged**
