### PR TITLE
Test memory_limit=None for CUDAWorker

### PR DESCRIPTION
**Pull request by wence-**
This introduces a test that was a TODO in #944

### CODE REVIEW

**Comment by pentschev** [comment]
The errors seem to be from Tornado deprecations.

Could you add `ignore:clear_current is deprecated:DeprecationWarning:tornado` to https://github.com/rapidsai/dask-cuda/blob/branch-22.08/pytest.ini#L6 ?

**Comment by wence-** [comment]
> The errors seem to be from Tornado deprecations.
> 
> Could you add `ignore:clear_current is deprecated:DeprecationWarning:tornado` to https://github.com/rapidsai/dask-cuda/blob/branch-22.08/pytest.ini#L6 ?

I've added the relevant lines, I hope, but let's wonder why this failure appeared, whereas it wasn't there yesterday.

This is a deprecation warning that appeared in tornado 6.2 (tornadoweb/tornado#3097), which was released yesterday. distributed added a pin for tornado<6.2, which is what is causing this problem, yesterday (https://github.com/dask/distributed/pull/6668). I guess that hasn't filtered down to the nightlies, because the failing run installed tornado==6.2.

**Comment by pentschev** [comment]
In any case I went ahead and attempted to fix the conda package as well in https://github.com/dask/distributed/pull/6675, so we may be able to remove the `DeprecationWarning` entry once that's merged.

**Comment by wence-** [comment]
Can't filter on `tornado` specifically, but hopefully this one will pass.

**Review by pentschev — APPROVED** [review]
LGTM, thanks @wence- .

**Comment by pentschev** [comment]
@gpucibot merge

**Pull request merged**
