### PR TITLE
Tests: replacing the obsolete cudf.testing._utils.assert_eq calls

### PR DESCRIPTION
**Pull request by madsbk**
Using `from dask.dataframe.utils import assert_eq` instead

### CODE REVIEW

**Review by pentschev — APPROVED** [review]
LGTM, thanks @madsbk !

**Comment by madsbk** [comment]
Thanks @pentschev, I suspect that the last CI error will be fixed with https://github.com/rapidsai/cudf/pull/9031

**Comment by madsbk** [comment]
@gpucibot merge

**Comment by pentschev** [comment]
rerun tests

**Comment by jakirkham** [comment]
Prem has a fix in PR ( https://github.com/dask/dask/pull/8055 )

**Comment by pentschev** [comment]
@jakirkham no, that doesn't fix it. I've commented about it in https://github.com/rapidsai/dask-cuda/pull/705#issuecomment-901342592 and chatted with him offline, he's gonna take a look at it.

**Comment by jakirkham** [comment]
Just to confirm, did you see this change ( https://github.com/dask/dask/pull/8055#pullrequestreview-733196001 )?

**Comment by pentschev** [comment]
> Just to confirm, did you see this change ( [dask/dask#8055 (review)](https://github.com/dask/dask/pull/8055#pullrequestreview-733196001) )?

Yes, I just tested that PR locally (specifically the current latest commit https://github.com/dask/dask/pull/8055/commits/42024016fe39c477587371f9d9ddd66c33e92658) and the dask-cuda still fail in my local environment.

**Comment by jakirkham** [comment]
Ok thanks. Noted that in the PR

**Comment by jakirkham** [comment]
rerun tests

**Pull request merged**
