### PR TITLE
Remove click pinning

### LINKED ISSUE #931: Overly precise `click==8.0.4` pin?
I have a project that uses `click==8.1.3` and `pip` is unhappy due to [dask-cuda's `click==8.0.4` pin](https://github.com/rapidsai/dask-cuda/blob/f93a02363d5aaf394c96fa2a57f4c0e7b586907f/requirements.txt#L6).

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 22.4.0 requires click==8.0.4, but you have click 8.1.3 which is incompatible.
```

Are there any known issues with other 8.x versions of `click`, or might e.g. `click>=8.0` suffice?

### PR DESCRIPTION
**Pull request by charlesbluca**
With the `click` breakage in Distributed presumably resolved, we should be good removing this click pinning.

Closes #931

### CODE REVIEW

**Review by pentschev — APPROVED** [review]
LGTM, thanks @charlesbluca .

**Comment by pentschev** [comment]
Yes, looks like a CI issue

**Comment by pentschev** [comment]
rerun tests

**Comment by jakirkham** [comment]
Suspect this CI issue is related to some other ones we have run into with CUDA Python not finding `libcuda.so`

cc @galipremsagar (for awareness)

**Comment by galipremsagar** [comment]
> Suspect this CI issue is related to some other ones we have run into with CUDA Python not finding `libcuda.so`
> 
> cc @galipremsagar (for awareness)

Yes, all of Rapids CI is currently blocked.

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
@gpucibot merge

**Pull request merged**
