### PR TITLE
Update PyNVML and set upper pin

### PR DESCRIPTION
**Pull request by wence-**
Handling the str vs. bytes discrepancy should have been covered by the changes in #1118.

### CODE REVIEW

**Comment by ajschmidt8** [comment]
There were two pins in the PR below, but only one unpin in this PR.

- https://github.com/rapidsai/dask-cuda/pull/1128/files

Should `pyproject.toml` also be unpinned?

**Review by ajschmidt8 — APPROVED** [review]

**Comment by jakirkham** [comment]
One CI job is [failing]( https://github.com/rapidsai/dask-cuda/actions/runs/4264828210/jobs/7423507907 ) with this error:

```python
Unable to start CUDA Context
Traceback (most recent call last):
  File "/opt/conda/envs/test/lib/python3.8/site-packages/pynvml/nvml.py", line 850, in _nvmlGetFunctionPointer
    _nvmlGetFunctionPointer_cache[name] = getattr(nvmlLib, name)
  File "/opt/conda/envs/test/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/opt/conda/envs/test/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib64/libnvidia-ml.so.1: undefined symbol: nvmlDeviceGetComputeRunningProcesses_v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/test/lib/python3.8/site-packages/dask_cuda/initialize.py", line 31, in _create_cuda_context
    distributed.comm.ucx.init_once()
  File "/opt/conda/envs/test/lib/python3.8/site-packages/distributed/comm/ucx.py", line 136, in init_once
    pre_existing_cuda_context = has_cuda_context()
  File "/opt/conda/envs/test/lib/python3.8/site-packages/distributed/diagnostics/nvml.py", line 219, in has_cuda_context
    if _running_process_matches(handle):
  File "/opt/conda/envs/test/lib/python3.8/site-packages/distributed/diagnostics/nvml.py", line 179, in _running_process_matches
    running_processes = pynvml.nvmlDeviceGetComputeRunningProcesses(handle)
  File "/opt/conda/envs/test/lib/python3.8/site-packages/pynvml/nvml.py", line 2608, in nvmlDeviceGetComputeRunningProcesses
    return nvmlDeviceGetComputeRunningProcesses_v3(handle);
  File "/opt/conda/envs/test/lib/python3.8/site-packages/pynvml/nvml.py", line 2576, in nvmlDeviceGetComputeRunningProcesses_v3
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetComputeRunningProcesses_v3")
  File "/opt/conda/envs/test/lib/python3.8/site-packages/pynvml/nvml.py", line 853, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_FUNCTION_NOT_FOUND)
pynvml.nvml.NVMLError_FunctionNotFound: Function Not Found
```

**Comment by jakirkham** [comment]
Rerunning CI to see if the Dask `2023.2.1` release helped

**Comment by wence-** [comment]
> Rerunning CI to see if the Dask `2023.2.1` release helped

I imagine the problem is that pynvml has been updated to require a v3 version of a function in nvml, but that doesn't exist in cuda 11.2?

**Comment by wence-** [comment]
This is WIP until such time as a solution for backwards compat is decided on in nvidia-ml-py (and/or pynvml). So until then we should just keep pynvml at 11.4.1

**Comment by jakirkham** [comment]
Going to double check this, but my understanding is we want PyNVML 11.5 for CUDA 12 support

**Comment by pentschev** [comment]
Agreed, but it seems we need that fix to land in nvidia-ml-py first as we can't work around that in a reasonable manner.

**Comment by pentschev** [comment]
This pending resolution of NVBug 4008080.

**Comment by jakirkham** [comment]
Curious where things landed here. AFAICT this is still pinned

**Review by jakirkham — APPROVED** [review]
Thanks Lawrence and Peter! 🙏

**Pull request merged**
