### PR TITLE
Install dependencies via meta package

### PR DESCRIPTION
**Pull request by raydouglass**
Install dependencies via `rapids-build-env` (which is pre-installed in the containers).

This brings the repo in line with https://docs.rapids.ai/maintainers/depmgmt/

Depends on https://github.com/rapidsai/integration/pull/49

### CODE REVIEW

**Comment by pentschev** [comment]
@raydouglass it seems like `pytest-asyncio` or a similar tool is missing in the failing test: https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fdask-cuda%2Fprb%2Fdask-cuda-gpu-build/detail/dask-cuda-gpu-build/1124/pipeline#log-1625 .

**Comment by jakirkham** [comment]
> @raydouglass it seems like `pytest-asyncio` or a similar tool is missing in the failing test: https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fdask-cuda%2Fprb%2Fdask-cuda-gpu-build/detail/dask-cuda-gpu-build/1124/pipeline#log-1625 .

Looks like that [has been added]( https://github.com/rapidsai/integration/blob/f14f5c900fcb02ae5e43b180af3bf6b566f9a776/conda/recipes/rapids-build-env/meta.yaml#L105 ).

**Comment by jakirkham** [comment]
rerun tests

**Comment by pentschev** [comment]
Thanks @jakirkham for confirming.

**Comment by raydouglass** [comment]
rerun tests

**Pull request merged**
