### PR TITLE
[NO MRG] Rerun CI w/PyNVML 12

### PR DESCRIPTION
**Pull request by jakirkham**
Following up on this comment ( https://github.com/rapidsai/dask-cuda/pull/1419#issuecomment-2556444021 ), this PR retests Dask-CUDA with PyNVML 12. As cuDF pinned PyNVML to 11 and Dask-CUDA depends on cuDF for testing, the previous Dask-CUDA PR could not test with PyNVML 12. This will help test Dask-CUDA with PyNVML 12 once cuDF packages are rebuilt with PyNVML 12 support ( https://github.com/rapidsai/cudf/pull/17627 )

### CODE REVIEW

**Comment by pentschev** [comment]
https://github.com/rapidsai/cudf/pull/17627 is now in, triggering CI.

**Comment by pentschev** [comment]
This is working, `conda-python-tests` logs show:

```
pynvml                    12.0.0             pyhd8ed1ab_0    conda-forge
```

I'll go ahead and close this as I think it served its purpose, but feel free to reopen if you think there's more to be checked @jakirkham .

**Comment by jakirkham** [comment]
Agreed. Thanks Peter! 🙏

**Pull request closed without merging**
