### PR TITLE
WIP: Add option to enable RMM logging

### PR DESCRIPTION
**Pull request by jakirkham**
Includes an option to enable RMM logging for Dask-CUDA workers.

cc @rlratzel @dillon-cullinan @shwina

### CODE REVIEW

**Comment by jakirkham** [comment]
Also adding a few bits upstream in PR ( https://github.com/dask/distributed/pull/3924 ).

**Comment by jakirkham** [comment]
With PR ( https://github.com/rapidsai/rmm/pull/466 ), RMM automatically includes the device ID in the log filename for us. So as long as we assume 1 worker per device (current procedure) we don't need to do anything special beyond choosing a name.

**Comment by pentschev** [comment]
@jakirkham do recent RMM changes make this easier to get this PR in?

**Comment by pentschev** [comment]
Is this change still relevant @jakirkham ?

**Comment by pentschev** [comment]
Is there still a wish in pursuing this @jakirkham ?

**Comment by pentschev** [comment]
@jakirkham ping. :)

**Comment by jakirkham** [comment]
Sorry for the lack of response. I think we still want this, but I don't have the bandwidth to pick it up currently. If someone wants to grab this, great. If not, I think it is fine for it to sit here.

**Comment by jakirkham** [comment]
Filing as issue ( https://github.com/rapidsai/dask-cuda/issues/522 ) and closing. This probably needs to be reworked since things have change in RMM (like CNMeM being removed for example).

**Pull request closed without merging**
