### PR TITLE
Pin max `dask` & `distributed` versions

### PR DESCRIPTION
**Pull request by galipremsagar**
Changes to be in-line with: https://github.com/rapidsai/cudf/pull/8859/

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
rerun tests

**Comment by pentschev** [comment]
The failure is because CI still installs Dask/Distributed main branch, and there's now some changes in Distributed on UCX variable name changing that need to be resolved in Dask-CUDA. I opened https://github.com/rapidsai/dask-cuda/pull/687 to avoid installing Dask from main branch and will revert that in 21.10 after that PR is merged.

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by pentschev** [comment]
https://github.com/rapidsai/dask-cuda/pull/687 is in, rerunning tests now.

**Comment by pentschev** [comment]
rerun tests

**Comment by jakirkham** [comment]
@gpucibot merge

**Pull request merged**
