### PR TITLE
Require Distributed 2.15.0+

### PR DESCRIPTION
**Pull request by jakirkham**
This is needed for serialization fixes when working with collections of objects (particularly when they contain 5+ elements).

xref: https://github.com/dask/distributed/pull/3689
xref: https://github.com/rapidsai/dask-cuda/pull/286

### CODE REVIEW

**Comment by jakirkham** [comment]
These failures seem unexpected. Posting here for tracking purposes, but will go ahead and restart CI (suspect they are spurious).

<details>

```python
=================================== FAILURES ===================================
_______________________ test_dataframe_merge[ucx-cudf-1] _______________________

backend = 'cudf', protocol = 'ucx', nworkers = 1

    @pytest.mark.parametrize("nworkers", [1, 2, 4])
    @pytest.mark.parametrize("backend", ["pandas", "cudf"])
    @pytest.mark.parametrize("protocol", ["tcp", "ucx"])
    def test_dataframe_merge(backend, protocol, nworkers):
        p = mp.Process(target=_test_dataframe_merge, args=(backend, protocol, nworkers))
        p.start()
        p.join()
>       assert not p.exitcode
E       assert not -11
E        +  where -11 = <SpawnProcess(SpawnProcess-12, stopped[SIGSEGV])>.exitcode

dask_cuda/tests/test_explicit_comms.py:90: AssertionError
_______________________ test_dataframe_merge[ucx-cudf-2] _______________________

backend = 'cudf', protocol = 'ucx', nworkers = 2

    @pytest.mark.parametrize("nworkers", [1, 2, 4])
    @pytest.mark.parametrize("backend", ["pandas", "cudf"])
    @pytest.mark.parametrize("protocol", ["tcp", "ucx"])
    def test_dataframe_merge(backend, protocol, nworkers):
        p = mp.Process(target=_test_dataframe_merge, args=(backend, protocol, nworkers))
        p.start()
        p.join()
>       assert not p.exitcode
E       assert not -11
E        +  where -11 = <SpawnProcess(SpawnProcess-13, stopped[SIGSEGV])>.exitcode

dask_cuda/tests/test_explicit_comms.py:90: AssertionError
_______________________ test_dataframe_merge[ucx-cudf-4] _______________________

backend = 'cudf', protocol = 'ucx', nworkers = 4

    @pytest.mark.parametrize("nworkers", [1, 2, 4])
    @pytest.mark.parametrize("backend", ["pandas", "cudf"])
    @pytest.mark.parametrize("protocol", ["tcp", "ucx"])
    def test_dataframe_merge(backend, protocol, nworkers):
        p = mp.Process(target=_test_dataframe_merge, args=(backend, protocol, nworkers))
        p.start()
        p.join()
>       assert not p.exitcode
E       assert not -11
E        +  where -11 = <SpawnProcess(SpawnProcess-14, stopped[SIGSEGV])>.exitcode

dask_cuda/tests/test_explicit_comms.py:90: AssertionError
```

</details>

https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fdask-cuda%2Fprb%2Fdask-cuda-gpu-build/detail/dask-cuda-gpu-build/1054/pipeline

**Comment by jakirkham** [comment]
rerun tests

**Comment by pentschev** [comment]
https://github.com/rapidsai/dask-cuda/pull/308 should fix errors.

**Comment by pentschev** [comment]
I just realized we probably want to update https://github.com/rapidsai/dask-cuda/blob/branch-0.15/conda/recipes/dask-cuda/meta.yaml#L28 too, what do you think @jakirkham ?

**Comment by pentschev** [comment]
rerun tests

**Comment by jakirkham** [comment]
> I just realized we probably want to update https://github.com/rapidsai/dask-cuda/blob/branch-0.15/conda/recipes/dask-cuda/meta.yaml#L28 too, what do you think @jakirkham ?

Yep you're right. Thanks for catching that 🙂

Latest commit should fix this.

**Comment by jakirkham** [comment]
Thanks Ray! 😄

**Comment by jakirkham** [comment]
Went ahead and merged. Hope that is ok. If you catching anything else, I can fix it in a follow-up.

**Pull request merged**
