### PR TITLE
[REVIEW] Remove max version pin for `dask` & `distributed` on development branch

### PR DESCRIPTION
**Pull request by galipremsagar**
This PR will remove max version pinning for dask & distributed for development purposes.

ref: rapidsai/cudf#8881

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by pentschev** [comment]
This will currently fail. We have to update UCX variables since https://github.com/dask/distributed/pull/4916 got merged, I'm still working on that.

**Review by jakirkham — APPROVED** [review]

**Comment by pentschev** [comment]
Changes from https://github.com/rapidsai/dask-cuda/pull/693 should hopefully fix build failures.

**Comment by jakirkham** [comment]
That seems to be linking to this PR. Was another PR intended?

**Comment by pentschev** [comment]
Ha! Yes, thanks for correcting that for me John! 😄

**Comment by jakirkham** [comment]
All good 🙂 Have done the same thing before 😅

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
@gpucibot merge

**Pull request merged**
