### PR TITLE
[REVIEW] Pin `dask` and `distributed` for release

### PR DESCRIPTION
**Pull request by galipremsagar**
Pinning to be in line with: https://github.com/rapidsai/cudf/pull/10987

### CODE REVIEW

**Comment by pentschev** [comment]
rerun tests

**Review by pentschev — APPROVED** [review]
Thanks @galipremsagar !

**Comment by galipremsagar** [comment]
@gpucibot merge

**Review by ajschmidt8 — APPROVED** [review]

**Comment by galipremsagar** [comment]
@gpucibot merge

**Pull request merged**
