### PR TITLE
[REVIEW] Fix registering correct dispatches for `cudf.Index`

### PR DESCRIPTION
**Pull request by galipremsagar**
Fixes: #715 

With the recent `cudf` refactor done in https://github.com/rapidsai/cudf/pull/8309, we will need to update `cudf.Index` to `cudf.BaseIndex` at these places.

### CODE REVIEW

**Review by quasiben — APPROVED** [review]

**Comment by quasiben** [comment]
Thanks @galipremsagar !

**Comment by quasiben** [comment]
@gpucibot merge

**Comment by galipremsagar** [comment]
Thanks for the quick review @quasiben ! 🎉

**Comment by jakirkham** [comment]
Thanks Prem! 😄

**Pull request merged**
