### PR TITLE
Change the updated new_worker_spec API for upstream

### PR DESCRIPTION
**Pull request by mrocklin**
This changed upstream in https://github.com/dask/distributed/pull/3000

Fixes https://github.com/rapidsai/dask-cuda/issues/128

cc @cjnolet

### CODE REVIEW

**Comment by mrocklin** [comment]
The failure here is just because this change depends on the master version of distributed.  I'm not sure if we want to pin dask-cuda to that yet.

**Comment by pentschev** [comment]
What would be the issue in pinning CI only to distributed master? We've done that in the past, unless there are some changes with distributed master that may break dask-cuda somehow, on which case we would need to fix it here first.

**Comment by mrocklin** [comment]
I think that I should probably make distributed more flexible in supporting
the older version here for a while.

**Comment by pentschev** [comment]
Alright, I've been working on issues in this repo today, and it seems like this fix is necessary, as well as updating to upstream distributed. This is the case for https://github.com/rapidsai/dask-cuda/pull/126 too.

@mrocklin the simplest is definitely just to make sure CI uses master, but over time this becomes an issue since we have to remember of removing that close to release dates to ensure the repo still works. Any ideas on how we could better treat issues with unreleased versions of dask/distributed?

**Comment by mrocklin** [comment]
One approach would be to move the dask-cuda release cycle in line with Dask rather than RAPIDS.  For the deployment work I tend to update all of the deployment solutions at each release and co-release them to avoid conflicts like this.

This pain is particular to deployment I think, which is undergoing heavy churn right now.  I'm hoping that this pain goes away in the next few months.

**Comment by pentschev** [comment]
I think in this particular case, the release cycle that dask-cuda is relying on doesn't make much difference. The issue here is that the latest distributed release breaks dask-cuda. The only real solution I see for this case (which has already happened before) is to pin to a specific version of dask and distributed, and then we should probably have dask-cuda updated to newer releases manually. Would you think this is a reasonable alternative?

Regardless of the release cycle discussion, I think we should for now make sure CI uses distributed's upstream to merge this PR and #126, so that the work on this repo can resume. Would you like to do it here or prefer that I do it (#126 will still require changes from this PR, so I would suggest we fix and merge this one first).

**Comment by mrocklin** [comment]
> The issue here is that the latest distributed release breaks dask-cuda.

Is it the latest release or is it that dask-cuda@master doesn't work with distributed@latest-release?

> The only real solution I see for this case (which has already happened before) is to pin to a specific version of dask and distributed, and then we should probably have dask-cuda updated to newer releases manually. 

For the other dask deployment projects (kubernetes, jobqueue) we tend to ensure that latest releases always support each other, and that master in each tends to support each other.  This seems to work out pretty well, and it doesn't require pinning environments, which folks will often avoid in Python, just because explicit pinning tends to create some havoc with complex environments.

> Would you think this is a reasonable alternative?

Sure, it's reasonable, especially during this period of deployment churn.  I'm somewhat in favor of co-releasing if that's feasible, but I'm happy to defer to your judgement here.  You've been doing most of the work here.

**Comment by pentschev** [comment]
> Is it the latest release or is it that dask-cuda@master doesn't work with distributed@latest-release?

Both, because dask-cuda 0.9 and master (aka, 0.10) install distributed>=2.3.0 (which is currently 2.3.2), but they work with distributed==2.3.0.

> For the other dask deployment projects (kubernetes, jobqueue) we tend to ensure that latest releases always support each other, and that master in each tends to support each other. This seems to work out pretty well, and it doesn't require pinning environments, which folks will often avoid in Python, just because explicit pinning tends to create some havoc with complex environments.

Yeah, that's a great point that I didn't think about.

> Sure, it's reasonable, especially during this period of deployment churn. I'm somewhat in favor of co-releasing if that's feasible, but I'm happy to defer to your judgement here. You've been doing most of the work here.

Unfortunately, your prior point (creating havoc on complex environments) feels like this would be a bad choice, which I would prefer to avoid. I think for now we should just point CI to distributed@master and revert that once there's a new distributed release. Would you like to do it or prefer that I submit a PR to your branch?

**Comment by mrocklin** [comment]
> Would you like to do it or prefer that I submit a PR to your branch?

As a maintainer you should have push access to my branch here.  Please feel free to push to any branch of mine to which you have access now or at any time in the future.

>  I think for now we should just point CI to distributed@master and revert that once there's a new distributed release.

Fine with me.  Once there is a distributed release (which will probably happen later this week) what happens with dask-cuda?  The latest releases of both projects will probably not be consistent.  Normally I would publish a release of dask-foo when this happens, but I'm not sure we can do that with the current RAPIDS release procedure.

**Comment by pentschev** [comment]
> As a maintainer you should have push access to my branch here. Please feel free to push to any branch of mine to which you have access now or at any time in the future.

Will do.

> Fine with me. Once there is a distributed release (which will probably happen later this week) what happens with dask-cuda? The latest releases of both projects will probably not be consistent. Normally I would publish a release of dask-foo when this happens, but I'm not sure we can do that with the current RAPIDS release procedure.

We can then remove that install from CI and simply let the latest version to get installed (as should be the case since it now installs `distributed>=2.3.0`). I think this will be automatically solved when the latest release gets installed, unless users pin to a specific version (such as `distributed=2.3.2`), in which case they're out of luck.

**Comment by pentschev** [comment]
Ok, this passes now, I'm merging it. Thanks for the fix @mrocklin !

**Pull request merged**
