### PR TITLE
Treat Deprecation/Future warnings as errors

### LINKED ISSUE #666: Raise errors in CI on `dask` / `distributed` deprecations
There's been interest from some Dask maintainers and folks on the RAPIDS team in Dask being more explicit about its public API. As a result we've started deprecating some utilities in `dask` and `distributed` (xref https://github.com/dask/distributed/pull/4966, https://github.com/dask/dask/pull/7810) and will eventually start making some methods private by prepending a leading underscore (`_`) to their name. We're planning to do this transition smoothly by raising `FutureWarning`s / `DeprecationWarning`s ahead of time to inform Dask users of any upcoming changes. 

In light of this, is there any interest for `dask-cuda` (or other RAPIDS projects which use Dask) to start raising errors in CI on `FutureWarning`s / `DeprecationWarning`s which are raised from `dask` or `distributed`? This will help give `dask-cuda` developers a heads up on upcoming changes. 

cc @rjzamora

### PR DESCRIPTION
**Pull request by pentschev**
This will allow us to know about and resolve Dask deprecation cycles more quickly.

Fixes #666

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks @pentschev!

FWIW, to your point in https://github.com/rapidsai/dask-cuda/issues/666#issuecomment-879404979, it should be possible to only raise on warnings which are coming from specific libraries ([here's how we target specific librarires like `numpy` and `pandas` over in `dask`](https://github.com/dask/dask/blob/7e231a17c04345f6f6cd66660db4a0df0f11b2ec/setup.cfg#L48-L51))

**Comment by pentschev** [comment]
> FWIW, to your point in [#666 (comment)](https://github.com/rapidsai/dask-cuda/issues/666#issuecomment-879404979), it should be possible to only raise on warnings which are coming from specific libraries ([here's how we target specific librarires like `numpy` and `pandas` over in `dask`](https://github.com/dask/dask/blob/7e231a17c04345f6f6cd66660db4a0df0f11b2ec/setup.cfg#L48-L51))

Aha! That's good to know, thanks @jrbourbeau . I'll try it as is for now to see how it behaves, but if that becomes too demanding I'll limit it to Dask/Distributed only.

**Review by Ethyling — APPROVED** [review]

**Comment by quasiben** [comment]
Thanks @pentschev !

**Comment by quasiben** [comment]
@gpucibot merge

**Review by quasiben — APPROVED** [review]

**Pull request merged**
