### PR TITLE
Don't install Dask main branch in CI for 21.08 release

### PR DESCRIPTION
**Pull request by pentschev**

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Peter! 😄

**Review by raydouglass — APPROVED** [review]

**Comment by jakirkham** [comment]
rerun tests

(needed to clear up `dask-cudf` duplicate package issue)

**Comment by pentschev** [comment]
@gpucibot merge

**Comment by pentschev** [comment]
Thanks John and Ray for reviews!

**Pull request merged**
