### PR TITLE
Standardize Distributed config separator in get_ucx_config

### PR DESCRIPTION
**Pull request by pentschev**
Some of the UCX configurations used `_` whereas others used `-` as a separator. This has been standardized in https://github.com/dask/distributed/pull/5539, and this updates Dask-CUDA to the new standard.

### CODE REVIEW

**Comment by pentschev** [comment]
rerun tests

**Review by madsbk — APPROVED** [review]
Looks good @pentschev, thanks.

**Comment by pentschev** [comment]
@gpucibot merge

**Comment by pentschev** [comment]
Thanks @madsbk !

**Pull request merged**
