### PR TITLE
added versioning capability

### PR DESCRIPTION
**Pull request by paulhendricks**

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by paulhendricks** [comment]
@mrocklin @randerzander

**Comment by paulhendricks** [comment]
Talking with @randerzander, this would be a "Nice to Have" feature: https://github.com/rapidsai/dask-cuda/issues/28

Should versioning start at 0.1? At 0.6/0.7?

**Comment by mrocklin** [comment]
You will also want to mirror this change in the `setup.py` file so that it affects PyPI downloads.  

I don't have a preference around which version number we use.

**Comment by mrocklin** [comment]
An alternative would be to use a project like versioneer, which would generate version numbers given git tags.  A number of other projects do this.  This is fine too though.

**Comment by raydouglass** [comment]
rerun tests

**Comment by pentschev** [comment]
#88 was merged yesterday, and should improve versioning. Closing now, but feel free to open a new PR if something is still missing.

**Pull request closed without merging**
