### PR TITLE
[REVIEW] Pin `dask` and `distributed` for release

### PR DESCRIPTION
**Pull request by galipremsagar**
This PR pins `dask` and `distributed` to `2022.11.1` for `22.12` release.

xref: https://github.com/rapidsai/cudf/pull/12165

### CODE REVIEW

**Comment by galipremsagar** [comment]
cc: @pentschev for review

**Comment by pentschev** [comment]
I think we should wait until codefreeze, burndown is starting only tomorrow. Any reasons why we should do it this early?

**Comment by galipremsagar** [comment]
> I think we should wait until codefreeze, burndown is starting only tomorrow. Any reasons why we should do it this early?

We can wait if you would want us to across all repos. cudf code-freeze begins tomorrow, hence opening the PRs for all repos.

**Comment by pentschev** [comment]
I guess it makes sense to pin it down once we are somewhat confident this is the version we want. Since code freeze for ["others" (including Dask) starts December 1st](https://docs.rapids.ai/maintainers), I'm imagining there will be another Dask release until then. I have no strong objections on doing this immediately, but if we do this is effectively a code-freeze regarding Dask, which is what we wanted to avoid.

**Review by raydouglass — APPROVED** [review]

**Review by pentschev — CHANGES_REQUESTED** [review]
Momentarily blocking this to raise a discussion.

**Comment by pentschev** [comment]
Per our discussion, we decided we should pin during the second code freeze, for the upcoming release that is December 1st. I added the "blocked" label for this PR, which we can on that date update and merge. Thanks so much @galipremsagar for your effort here, it's really appreciated! 😄

**Comment by galipremsagar** [comment]
pinging @pentschev for review

**Review by pentschev — APPROVED** [review]
LGTM, thanks @galipremsagar !

**Comment by pentschev** [comment]
@gpucibot merge

**Pull request merged**
