### PR TITLE
Explicit-comms: lock workers

### PR DESCRIPTION
**Pull request by madsbk**
This PR uses https://github.com/dask/distributed/pull/4503 to support locking of workers before submitting an explicit-comms job.

- [x] Implement `CommsContext.run(..., lock_workers=False)`
- [x] Implement tests

### CODE REVIEW

**Comment by madsbk** [comment]
> This PR has been labeled `inactive-30d` due to no recent activity in the past 30 days. Please close this PR if it is no longer required. Otherwise, please respond with a comment indicating any updates. This PR will be labeled `inactive-90d` if there is no activity in the next 60 days.

Waiting for https://github.com/dask/distributed/pull/4503 to be merged, which should hopefully happen soon.

**Review by pentschev — APPROVED** [review]
LGTM, thanks @madsbk .

**Comment by pentschev** [comment]
@quasiben I think you'll need to authorize this if we still want to have it in 0.19, otherwise we should retarget it.

**Comment by quasiben** [comment]
Do you think this is critical for 0.19?  I'm somewhat inclined to wait but keen to hear your thoughts @madsbk / @pentschev

**Comment by pentschev** [comment]
I think this is more of a question for @madsbk , is it important for 0.19?

**Comment by madsbk** [comment]
> I think this is more of a question for @madsbk , is it important for 0.19?

Not at all, re-targeting to `branch-0.20`

**Comment by pentschev** [comment]
Failures are happening across all PRs, I've opened https://github.com/rapidsai/dask-cuda/issues/564 to track this.

**Comment by madsbk** [comment]
@gpucibot merge

**Pull request merged**
