### PR TITLE
Add --protocol flag to dask-cuda-worker

### LINKED ISSUE #667: dask-cuda-worker isn't able to connect to dask-scheduler using websocket protocol...
```
(rapids) root@2103694:/rapids/notebooks# dask-scheduler --version
dask-scheduler, version 2021.6.1

(rapids) root@2103694:/rapids/notebooks# dask-worker --version
dask-worker, version 2021.6.1

(rapids) root@2103694:/rapids/notebooks# pip list | grep -i dask
dask                          2021.6.1
dask-cuda                     0+untagged.1.gf3220a4
dask-cudf                     0+untagged.1.g788bddd
dask-glm                      0.2.0
dask-labextension             5.0.2
dask-ml                       1.9.0
```

dask scheduler is running on standard ports using `ws` procotol. traffic to it is proxied.

```
root          1      0  0 19:13 ?        00:00:00 /bin/sh -c /opt/docker/bin/entrypoint --unquote-exec dask-scheduler --dashboard-address :8787 --port 8786 --protocol ws
root          6      1  3 19:13 ?        00:00:24 /opt/conda/envs/rapids/bin/python /opt/conda/envs/rapids/bin/dask-scheduler --dashboard-address :8787 --port 8786 --protocol ws
```

i'm trying to connect to this scheduler from another node using both `dask-cuda-worker` and `dask-worker`.

`dask-worker` is able to connect, but *not* `dask-cuda-worker`

```
(rapids) root@2103694:/rapids/notebooks# dask-worker wss://proxy_endpoint:443 --protocol ws
distributed.nanny - INFO -         Start Nanny at: 'ws://100.103.223.134:40227'
distributed.worker - INFO -       Start worker at: ws://100.103.223.134:44835
distributed.worker - INFO -          Listening to: ws://100.103.223.134:44835
distributed.worker - INFO -          dashboard at:      100.103.223.134:42105
distributed.worker - INFO - Waiting to connect to: wss://proxy_endpoint:443
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          8
distributed.worker - INFO -                Memory:                  50.00 GiB
distributed.worker - INFO -       Local Directory: /rapids/notebooks/dask-worker-space/worker-764djlbo
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to: wss://proxy_endpoint:443
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection

```

`dask-cuda-worker`

```
(rapids) root@2103694:/rapids/notebooks# dask-cuda-worker wss://proxy_endpoint:443 --protocol ws
Usage: dask-cuda-worker [OPTIONS] [SCHEDULER] [PRELOAD_ARGV]...

Error: no such option: --protocol
```

tried without the `--protocol`

```
(rapids) root@2103694:/rapids/notebooks# dask-cuda-worker wss://proxy_endpoint:443
...

TypeError: TLS expects a `ssl_context` argument of type ssl.SSLContext (perhaps check your TLS configuration?)  Instead got None
```

@jacobtomlinson - fyi.

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Closes #667

### CODE REVIEW

**Comment by pentschev** [comment]
I would prefer that this is handled by Distributed, as per https://github.com/rapidsai/dask-cuda/issues/667#issuecomment-878333408 .

**Review by pentschev — APPROVED** [review]
For now I agree this is a required feature, as per https://github.com/rapidsai/dask-cuda/issues/667#issuecomment-878393015 , thus approving.

@jacobtomlinson do you foresee this being important for `LocalCUDACluster` somehow too?

**Comment by jacobtomlinson** [comment]
@pentschev we may want to think about how to run `LocalCUDACluster` with both `ucx` and `ws` at some stage. But I do not think it is necessary right now.

**Comment by pentschev** [comment]
Thanks @jacobtomlinson .

**Comment by pentschev** [comment]
@gpucibot merge

**Pull request merged**
