### PR TITLE
Increate timeouts of tests that frequently timeout in CI

### PR DESCRIPTION
**Pull request by pentschev**
In the past few weeks some tests have timed out with certain frequency in CI, probably due to its load. Attempt to avoid those by increasing timeouts from 20 to 30 seconds.

### CODE REVIEW

**Comment by pentschev** [comment]
More examples of timeouts from last night: https://github.com/rapidsai/dask-cuda/actions/runs/6008227979/attempts/1

**Comment by wence-** [comment]
Those timeouts sadly still persist in this PR. Do we need to bump them further?

**Comment by pentschev** [comment]
I'm setting up locally to see if I can reproduce them and how long the average runtime seems to be on our systems. I'm wondering if this is only the timeout or there's something else hidden under the timeout error.

**Comment by pentschev** [comment]
Of course, now that the timeout has been increased there's nothing unusual, with `test_communicating_proxy_objects` taking < 10s every time. I think we may need to leave `--durations=0` for a few days and see it during the nightly tests, it looks to me like nightly tests fail because that's when we have the highest utilization of CI nodes when nightly tests are running for all projects, and thus things get slower.

What do you think we should do here @wence- ?

**Review by raydouglass — APPROVED** [review]

**Review by quasiben — APPROVED** [review]

**Comment by pentschev** [comment]
@wence- was trying to get this merged today but it seems [today's not the day to merge it](https://www.githubstatus.com/incidents/wqv4yvlgtq62). 😞

**Pull request merged**
