### PR TITLE
Remove kwargs from `LocalCUDACluster`

### PR DESCRIPTION
**Pull request by charlesbluca**
Based on some discussions in #561, this PR removes some kwargs from `LocalCUDACluster` that may not be needed:

- `processes` doesn't have any impact on its construction (other than throwing a `ValueError` if it's set false); this should be safe to remove altogether
- `data` is pretty complex and it isn't commonly specified, so it can be removed from the named arguments and accessed through the `kwargs` object if it is specified

### CODE REVIEW

**Comment by jakirkham** [comment]
Should `data` be dropped from the `super` call below since it is now in `kwargs`?

**Comment by charlesbluca** [comment]
I don't think so, as `data` is still assigned a value later on:

https://github.com/rapidsai/dask-cuda/blob/7a6be90e1a72d1caec7f77ce1221d8d6c31134c4/dask_cuda/local_cuda_cluster.py#L238-L255

**Comment by jakirkham** [comment]
In that case should we pop it from `kwargs`? Otherwise it is being passed twice to `super`. Once explicitly and once implicitly

**Comment by charlesbluca** [comment]
Yes! Thanks, I missed that.

**Review by pentschev — APPROVED** [review]
LGTM, thanks @charlesbluca !

**Comment by jakirkham** [comment]
Should add we will need to do the same thing for `processes`

**Comment by pentschev** [comment]
> Should add we will need to do the same thing for `processes`

Actually it just seems like we have a bunch of tests that explicitly pass `processes=True`, we are better off removing those instead. Could you do that @charlesbluca ?

**Comment by charlesbluca** [comment]
Done! Should we check if `processes` is provided as a kwarg and make sure to pop it so it doesn't end up in the super call?

**Comment by pentschev** [comment]
> Done! Should we check if `processes` is provided as a kwarg and make sure to pop it so it doesn't end up in the super call?

I don't mind leaving it as is as it isn't really supported, but if others prefer, we can pop from kwargs and reinstate the `ValueError` exception.

**Comment by jakirkham** [comment]
Continuing to raise an error makes sense as this should make it clearer that it is unsupported (as opposed to erroring when it is passed again to `super`). Maybe we can just check `if not kwargs.pop("processes", True)`?

**Comment by pentschev** [comment]
Failures are happening across all PRs, I've opened https://github.com/rapidsai/dask-cuda/issues/564 to track this.

**Comment by pentschev** [comment]
@charlesbluca I retargeted this to branch-0.20 since we're in code freeze and this isn't really a very high priority change for 0.19, better keep it safe.

**Comment by pentschev** [comment]
> That's fine! Should I have permissions to retarget PRs? #561 #563 should also be retargetted since those are low priority.

Yes, you should be able to do that by clicking "Edit" next to the PR title, then changing to branch-0.20 from the drop-down list where branch-0.19 is currently selected.

**Comment by jakirkham** [comment]
Went ahead and just retargeted those as well. Hope that is ok 🙂

**Comment by charlesbluca** [comment]
Thanks @jakirkham!

**Comment by pentschev** [comment]
@gpucibot merge

**Pull request merged**
