### PR TITLE
Add new reset_device_memory_limit utility function

### PR DESCRIPTION
**Pull request by pentschev**
New utility function that allows resetting a worker's `device_memory_limit` at cluster runtime.

### CODE REVIEW

**Comment by pentschev** [comment]
@beckernick I don't know of a good test for this right now, but could you try this out and see if it works in the context of #280 ?

**Comment by beckernick** [comment]
Thanks @pentschev . We'll test this and report back in this issue

**Comment by pentschev** [comment]
@beckernick friendly reminder to check when you have a chance. :)

**Comment by beckernick** [comment]
Thanks for the bump @pentschev . Will try to give this a spin in the next day or so.

**Comment by jakirkham** [comment]
We may want to update the target branch here. Looks like it shows `branch-0.14` currently.

**Comment by pentschev** [comment]
@beckernick is this still relevant for you?

**Comment by pentschev** [comment]
I'm closing this PR for now, as https://github.com/rapidsai/dask-cuda/issues/280#issuecomment-735986781 confirmed this is not immediately relevant. Should circumstances change, we can use this PR as a reference.

**Pull request closed without merging**
