### PR TITLE
Update dask and distributed versions on conda recipe

### LINKED ISSUE #87: [BUG] dask-cuda(0.7.0) is broken with latest distributed(2.0.1)
dask-cuda is not compatible with latest `distributed` 

Log:-
```
(base) builder@5ab0d442c86f:~$ dask-cuda-worker
Traceback (most recent call last):
  File "/opt/anaconda3/bin/dask-cuda-worker", line 11, in <module>
    load_entry_point('dask-cuda==0.7.0', 'console_scripts', 'dask-cuda-worker')()
  File "/opt/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/opt/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/opt/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/anaconda3/lib/python3.6/site-packages/dask_cuda/dask_cuda_worker.py", line 12, in <module>
    from distributed.worker import _ncores
ImportError: cannot import name '_ncores'
(base) builder@5ab0d442c86f:~$
```

Conda package :- 

```
(base) builder@5ab0d442c86f:~$ conda list | grep distributed
distributed               2.0.1                      py_0
(base) builder@5ab0d442c86f:~$

(base) builder@5ab0d442c86f:~$ conda list | grep dask
dask                      2.0.0                      py_0
dask-core                 2.0.0                      py_0
dask-cuda                 0.7.0           py36_489.g8bce79e    
dask-cudf                 0.9.0a          py36_493.g2167909    
(base) builder@5ab0d442c86f:~$

```

### PR DESCRIPTION
**Pull request by pentschev**
Fixes #87

### CODE REVIEW

**Comment by pentschev** [comment]
The version of distributed wasn't updated before the 0.8 release, but it dask-cuda requires distributed >=2.0 to work properly.

@mrocklin could you take a quick look at the update?

@dillon-cullinan is it possible for us to release an updated conda package for dask-cuda? The current 0.8.0 package is wrong on its dask/distributed dependency.

**Comment by mrocklin** [comment]
This change is fine to me.  Do we want it to target 0.9 instead?

**Comment by pentschev** [comment]
I think we should target 0.8, the current release may not work if distributed < 2.0.0.

**Comment by pentschev** [comment]
Closing this, as it's no longer relevant now that 0.8 is old stable.

**Pull request closed without merging**
