### PR TITLE
fix rmm_pool arg name in docs

### PR DESCRIPTION
**Pull request by quasiben**
cc @pentschev

### CODE REVIEW

**Comment by pentschev** [comment]
Thanks @quasiben , could you also fix https://github.com/rapidsai/dask-cuda/blob/e93ca001a2e8e2679c18824e8c5f8efb3d601c0e/dask_cuda/local_cuda_cluster.py#L103 ?

**Comment by quasiben** [comment]
Definitely!  My grepping missed that one.  Fixing now

**Comment by quasiben** [comment]
D'oh i forgot the skip ci line :(

**Comment by pentschev** [comment]
> D'oh i forgot the skip ci line :(

Next time. :)

**Pull request merged**
