### PR TITLE
Replace compute() calls on CuPy benchmarks by persist()

### PR DESCRIPTION
**Pull request by pentschev**
Based on the discussion from https://github.com/rapidsai/dask-cuda/issues/536, the CuPy benchmarks were using `compute()` instead of `persist()`, thus causing the data to be sent back to the client, and our intent is not to benchmark that step, this PR fixes that behavior.

I've targeted branch-0.19 for now because of the code freeze, it isn't 100% critical IMO to have this in 0.18, but certainly I'd prefer that. WDYT @quasiben @jakirkham ?

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Sounds good. Thanks Peter! 😄

Looks like there is a conflict that we might need to fix first

**Comment by pentschev** [comment]
> Sounds good. Thanks Peter! 😄

What sounds good, the fix or targeting branch-0.19?

> Looks like there is a conflict that we might need to fix first

Indeed, thanks for the heads up, should be fixed now! 🙂

**Comment by pentschev** [comment]
I'm merging this, since all tests pass after resolving conflicts. Thanks @jakirkham for the review!

**Comment by pentschev** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
> > Sounds good. Thanks Peter! 😄
> 
> What sounds good, the fix or targeting branch-0.19?

Both 😄 Sorry for being unclear

> > Looks like there is a conflict that we might need to fix first
> 
> Indeed, thanks for the heads up, should be fixed now! 🙂

Thanks Peter!

**Pull request merged**
