### PR TITLE
Proxify register lazy

### LINKED ISSUE #491: CUDA initialization error in `proxify_device_objects.py`
[Latest nightly tests](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/nightly-tests/job/docker-test-dask-cuda/lastCompletedBuild/CUDA_VER=11.0,DOCKER_REPO=rapidsai%2Frapidsai-dev-nightly,LINUX_VER=ubuntu16.04,PYTHON_VER=3.7,RAPIDS_VER=0.18/console) failed due to CUDA initialization error, which seems to be rooted at https://github.com/rapidsai/dask-cuda/blob/cd8a87d443aa1a283f042019aa673f531a3cda4e/dask_cuda/proxify_device_objects.py#L92 . I believe what's happening is that this is an import in the global level where dask-cuda can't ensure the CUDA context has already been created, in turn leaving that task then to cuDF.

@madsbk could you check if it's possible to move that import from the global level to a local one, in such a way as to prevent `cudf` from ever being imported before dask-cuda has had a chance to initialize the CUDA context? I took a quick look but it seems that this is an indirect dependency and I wasn't sure how to fix it without risking breaking something else.

### PR DESCRIPTION
**Pull request by madsbk**
Fixes #491 by moving dispatch of cudf objects within a `register_lazy("cudf")`.

### CODE REVIEW

**Comment by madsbk** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
Heh, sorry I asked for a rerun at the same time as you @madsbk .

**Comment by madsbk** [comment]
> Heh, sorry I asked for a rerun at the same time as you @madsbk .

Hehe :) 
`gpuCI/dask-cuda/gpu/cuda/11.0/python/3.8/ubuntu18.04` still fails though

**Review by pentschev — APPROVED** [review]
LGTM, thanks @madsbk for this PR!

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
> > Heh, sorry I asked for a rerun at the same time as you @madsbk .
> 
> Hehe :)
> `gpuCI/dask-cuda/gpu/cuda/11.0/python/3.8/ubuntu18.04` still fails though

Yes, trying one last time, if that fails again I'll raise it with devops.

**Comment by pentschev** [comment]
It failed again. @rapidsai/ops-codeowners could you please take a look in the `gpuCI/dask-cuda/gpu/cuda/11.0/python/3.8/ubuntu18.04` build? It's failing right at the beginning during `nvidia-smi -L`.

**Comment by madsbk** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Pull request merged**
