### PR TITLE
gc.collect when spilling on demand

### PR DESCRIPTION
**Pull request by madsbk**
When spilling on demand,  we now call `gc.collect()`.

### CODE REVIEW

**Review by pentschev — APPROVED** [review]
LGTM, thanks @madsbk !

**Comment by pentschev** [comment]
Apologies, clicked the wrong button and closed by accident.

**Comment by madsbk** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
@gpucibot merge

**Comment by pentschev** [comment]
Thanks @madsbk !

**Pull request merged**
