### PR TITLE
Fixes for handling MIG devices

### PR DESCRIPTION
**Pull request by pentschev**
Addresses errors reported recently in https://github.com/rapidsai/dask-cuda/issues/583#issuecomment-1181505348 . Depends on https://github.com/dask/distributed/pull/6720 .

### CODE REVIEW

**Comment by wence-** [comment]
rerun tests

**Comment by jacobtomlinson** [comment]
rerun tests

**Review by wence- — APPROVED** [review]
I think this looks right, do you need to temporarily point at the distributed branch for CI to pass?

**Comment by pentschev** [comment]
> I think this looks right, do you need to temporarily point at the distributed branch for CI to pass?

I think we're fine waiting until https://github.com/dask/distributed/pull/6720 is merged, in hindsight I should have waited before marking this ready for review, I thought that one would be working by now.

**Review by wence- — APPROVED** [review]
Looks good, thanks!

**Comment by pentschev** [comment]
@gpucibot merge

**Comment by pentschev** [comment]
Thanks @wence- for the review!

**Pull request merged**
