### PR TITLE
Remove support for UCX < 1.11.1

### PR DESCRIPTION
**Pull request by pentschev**
And about another ~500 fewer lines of fun here too.

Preparing for UCX-Py complete drop of UCX < 1.11.1 in https://github.com/rapidsai/ucx-py/pull/829.

### CODE REVIEW

**Review by madsbk — APPROVED** [review]
Awesome!

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
Thanks @madsbk for reviewing!

**Comment by pentschev** [comment]
@gpucibot merge

**Pull request merged**
