### PR TITLE
[WIP] Python CodeCov integration

### PR DESCRIPTION
**Pull request by dillon-cullinan**
Throwing in a fix that allows `--skip-tests` to be used properly with the `source` command.

### CODE REVIEW

**Comment by pentschev** [comment]
Same here, tests will fail until #90 is merged.

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
LGTM. Anything else to be done or can this be merged @dillon-cullinan?

**Comment by dillon-cullinan** [comment]
Good to merge :)

**Comment by pentschev** [comment]
Thanks for adding codecov @dillon-cullinan, I will soon check if it coverage can be improved!

**Pull request merged**
