### PR TITLE
Use PyNVML 12

### PR DESCRIPTION
**Pull request by jakirkham**
Bump `pynvml` from `11` to `12`. This version of `pynvml` also now depends on `nvidia-ml-py` for core functionality.

### CODE REVIEW

**Comment by jakirkham** [comment]
As cuDF is a test dependency ( https://github.com/rapidsai/cudf/pull/17627 ), we still pick up PyNVML 11 in some places

Think we will need to get one of these PRs in first (perhaps this one?) then come back and retest once cuDF is also built

**Review by jameslamb — APPROVED** [review]
Not strictly related to this PR's changes, but they'd help us build confidence in this and future `pynvml`-related changes... since `pynvml` is a hard runtime dependency, could we switch to using it **unconditionally** in tests, by removing stuff like this?

https://github.com/rapidsai/dask-cuda/blob/fd8a73659c89fc5d2678a6343002f7a2fc0a1a1f/dask_cuda/tests/test_utils.py#L200

https://github.com/rapidsai/dask-cuda/blob/fd8a73659c89fc5d2678a6343002f7a2fc0a1a1f/dask_cuda/tests/test_utils.py#L253

Think those skips could potentially cover up some packaging issues. I'd support trying to remove those right here in this PR, but also fine if you want to do it as a follow-up.

**Comment by pentschev** [comment]
> Not strictly related to this PR's changes, but they'd help us build confidence in this and future `pynvml`-related changes... since `pynvml` is a hard runtime dependency, could we switch to using it **unconditionally** in tests, by removing stuff like this?

I agree that's sensible. @jakirkham do you want to address this in this PR or would you prefer I do that in a separate PR?

**Comment by jakirkham** [comment]
As discussed offline, this is being handled in PR: https://github.com/rapidsai/dask-cuda/pull/1421

**Comment by jakirkham** [comment]
Thanks James and Peter! 🙏

Looks like it is passing. Let's get this in :shipit:

**Comment by jakirkham** [comment]
Fixed issue: https://github.com/rapidsai/dask-cuda/issues/1117

**Pull request merged**
