### PR TITLE
Install Dask + Distributed from `main`

### PR DESCRIPTION
**Pull request by jakirkham**
These recently dropped the `master` branch and switched to `main`. So update the install steps to use `main` instead.

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Review by quasiben — APPROVED** [review]

**Review by quasiben — APPROVED** [review]

**Comment by jakirkham** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Seems like we are getting some explicit comms test failures. @rjzamora would you be able to take a look? 🙂

**Comment by pentschev** [comment]
The issues seem to be GPU-related in CI:

```
22:30:30 [100] Call to cuInit results in CUDA_ERROR_NO_DEVICE:
22:30:31 Coverage.py warning: --include is ignored because --source is set (include-ignored)
22:30:31 Coverage.py warning: --include is ignored because --source is set (include-ignored)
22:30:31 Unable to start CUDA Context
22:30:31 Traceback (most recent call last):
22:30:31   File "/opt/conda/envs/rapids/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 237, in initialize
22:30:31     self.cuInit(0)
22:30:31   File "/opt/conda/envs/rapids/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 300, in safe_cuda_api_call
22:30:31     self._check_error(fname, retcode)
22:30:31   File "/opt/conda/envs/rapids/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 335, in _check_error
22:30:31     raise CudaAPIError(retcode, msg)
22:30:31 numba.cuda.cudadrv.driver.CudaAPIError: [100] Call to cuInit results in CUDA_ERROR_NO_DEVICE
```

Rerunning to see if this unblocks.

**Comment by jakirkham** [comment]
Seeing this in [the log]( https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/dask-cuda/job/prb/job/dask-cuda-gpu-test/CUDA=10.1,GPU_LABEL=gpu-t4%7C%7Cgpu,OS=ubuntu16.04,PYTHON=3.7/268/console )

```
10:58:40   File "/opt/conda/envs/rapids/lib/python3.7/site-packages/ucp/core.py", line 628, in recv
10:58:40     ret = await comm.tag_recv(self._ep, buffer, nbytes, tag, name=log)
10:58:40 ucp.exceptions.UCXMsgTruncated: <[Recv #112] ep: 0x7f0e25cde0d8, tag: 0xfa85496d273cdec2, nbytes: 260, type: <class 'numpy.ndarray'>>: length mismatch: 16 (got) != 260 (expected)
```

**Comment by jakirkham** [comment]
Wondering if that last part is related to PR ( https://github.com/dask/distributed/pull/4531 )

cc @madsbk (in case you have any thoughts here 🙂)

**Comment by jakirkham** [comment]
Sure marked as `xfail`. Raised issue ( https://github.com/rapidsai/dask-cuda/issues/549 ) to track and included this in the `xfail` message

**Review by pentschev — APPROVED** [review]
LGTM, thanks @jakirkham !

**Comment by pentschev** [comment]
@jakirkham seems like https://github.com/rapidsai/dask-cuda/blob/f52018694897ea7877e6c119a69765c99600f930/dask_cuda/tests/test_explicit_comms.py#L248 should also be xfailed. Could you do that as well?

**Comment by jakirkham** [comment]
Good catch! Thanks Peter 😄

Sorry had missed that earlier. Should be addressed now 🙂

**Pull request merged**
