### PR TITLE
[REVIEW] Add ucx-py dependency to conda recipe

### PR DESCRIPTION
**Pull request by raydouglass**

### CODE REVIEW

**Comment by pentschev** [comment]
For CI, it's indeed important to have UCX-Py installed. I'm not sure if we should make it a dependency in the conda package though, since dask-cuda should be perfectly usable without it.

Ideas @madsbk @quasiben @jakirkham @mrocklin ?

**Comment by quasiben** [comment]
dask-cuda as builid dependency definitely makes sense.  ucx-py is not really a dependency for dask-cuda to work properly.  ucx-py is still nascent and making it a dependency is a little risky.  Additionally,   If dask-cuda wants to continue supporting pip, depending on ucx-py would break this as it currently only supports conda

**Comment by pentschev** [comment]
Indeed. @raydouglass could we keep UCX-Py as a dependency to CI but remove that from the conda package?

**Comment by pentschev** [comment]
LGTM, thanks @raydouglass

**Pull request merged**
