### PR TITLE
Do not dispatch removed `cudf.Frame._index` object 

### PR DESCRIPTION
**Pull request by pentschev**
The object was removed in https://github.com/rapidsai/cudf/pull/11210.

### CODE REVIEW

**Comment by pentschev** [comment]
cc @madsbk

**Review by madsbk — APPROVED** [review]
LGTM, thanks @pentschev

**Comment by pentschev** [comment]
Thanks @madsbk for the fix here!

**Comment by pentschev** [comment]
@gpucibot merge

**Pull request merged**
