### PR TITLE
Fix owner check when the owner is a cupy array

### PR DESCRIPTION
**Pull request by wence-**
A cupy array can't be used in a boolean setting (it is neither truthy nor falsy because at heart it's intuitionist) so we need to explicitly check that the owner is None.

### CODE REVIEW

**Comment by wence-** [comment]
What's the right way to write a test for this?

**Review by madsbk — APPROVED** [review]
Thanks @wence- !

**Comment by madsbk** [comment]
> What's the right way to write a test for this?

Test with  a cupy array in `test_cudf_get_device_memory_objects`

**Comment by madsbk** [comment]
@gpucibot merge

**Pull request merged**
