### PR TITLE
Revert RMM init change

### PR DESCRIPTION
**Pull request by jakirkham**
As RMM now delays CUDA initialization (and doesn't include this environment variable) ( https://github.com/rapidsai/rmm/pull/493 ), we are able to revert this change.

cc @quasiben @pentschev @kkraus14 @harrism

### CODE REVIEW

**Comment by jakirkham** [comment]
Though we don't use this environment variable any more. Can we revisit once there is a need?

**Comment by quasiben** [comment]
I think we should switch `RAPIDS_NO_INITIALIZE` rather than removing.  This allows RAPIDS to generally set/search conditions where GPU initialization will be an issue.  They then could use this variable instead of `DASK_PARENT` as they do here: https://github.com/rapidsai/cudf/blob/d8705fe9ba02f9142ef2290068dedcde5dadbe16/python/cudf/cudf/utils/gpu_utils.py#L10

**Comment by pentschev** [comment]
> I think we should switch `RAPIDS_NO_INITIALIZE` rather than removing.

I'm in favor of using that variable, but when you say "switch", switch for what? Are you saying that cuDF should use that instead of `DASK_PARENT` as is done currently?

**Comment by quasiben** [comment]
> I'm in favor of using that variable, but when you say "switch", switch for what? Are you saying that cuDF should use that instead of DASK_PARENT as is done currently?

Yes, I believe @kkraus14 is on board with this switch as well, correct ?

**Comment by kkraus14** [comment]
Yes. Once `dask-cuda` uses `RAPIDS_NO_INITIALIZE` we'll switch to using that in cuDF as opposed to checking for the Dask environment variable.

**Comment by jakirkham** [comment]
Superseded by PR ( https://github.com/rapidsai/dask-cuda/pull/371 ).

**Pull request closed without merging**
