### PR TITLE
Fix a black error in explicit comms

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jakirkham** [comment]
CI failure will be fixed after PR ( https://github.com/rapidsai/dask-cuda/pull/359 ) is in.

**Comment by pentschev** [comment]
rerun tests

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
This is ok to merge (even with CUDA 11.0 failures outstanding).

**Pull request merged**
