### PR TITLE
pre-commit: spell, whitespace, and mypy check

### PR DESCRIPTION
**Pull request by madsbk**
close https://github.com/rapidsai/dask-cuda/issues/1077

### CODE REVIEW

**Review by pentschev — APPROVED** [review]
LGTM, thanks @madsbk . What's the idea moving forward, make mypy strict?

**Comment by madsbk** [comment]
> LGTM, thanks @madsbk . What's the idea moving forward, make mypy strict?

I think the first step is to install all the library stubs in CI. Currently, all lot of the code is ignored.

**Comment by wence-** [comment]
> > LGTM, thanks @madsbk . What's the idea moving forward, make mypy strict?
> 
> I think the first step is to install all the library stubs in CI. Currently, a lot of the code is ignored.

If we're using `pre-commit`, then we need to specify the extra packages in the pre-commit environment, so they all need to be pip installable (which might be problematic?)

**Pull request merged**
