### PR TITLE
Use upstream warning functions for CUDA initialization

### PR DESCRIPTION
**Pull request by charlesbluca**
Following up on https://github.com/dask/distributed/pull/6121, this PR uses Distributed's warning functions for CUDA initialization, cutting down on code duplication.

cc @pentschev

### CODE REVIEW

**Review by pentschev — APPROVED** [review]
LGTM, thanks @charlesbluca .

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Also PR ( https://github.com/dask/distributed/pull/6121 ) is part of the (currently in progress) `2022.4.1` `distributed` release

**Pull request merged**
