### PR TITLE
Add `__main__` entrypoint to dask-cuda-worker CLI

### LINKED ISSUE #1180: Make `dask_cuda.cli runnable` as a script with `python -m`
I am working towards fixing [#dask-jobqueue/229](https://github.com/dask/dask-jobqueue/issues/229) in which one would like to provide a parameter for which type of `worker` to start when using `jobqueue`

The call site currently looks like this:

```python
        # dask-worker command line build
        dask_worker_command = "%(python)s -m distributed.cli.dask_worker" % dict(
            python=python
        )
```

IE is called through `python -m`. 

`dask_cuda.cli` starts from `worker()` rather than `main` making  it incompatible with this call site. IMO it would be nice to homogenise these interfaces. 

I propose adding a very simple:

```python

if __name__ == "__main__":
    worker()

```
to `dask_cuda.cli` so that they can be called the same way.

### PR DESCRIPTION
**Pull request by hmacdope**
Fixes #1180 

Making the CLI runnable with `python -m ` so that we can use the same call for both CLIs in `dask-jobqueue`

### CODE REVIEW

**Review by wence- — APPROVED** [review]
I think this makes sense, thanks.

**Comment by pentschev** [comment]
Thanks @hmacdope !

**Review by pentschev — APPROVED** [review]

**Pull request merged**
