### PR TITLE
support space in workspace

### PR DESCRIPTION
**Pull request by jolorunyomi**
# Summary
This PR adds support for spaces in workspace

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Review by pentschev — APPROVED** [review]

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

**Comment by jakirkham** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Thanks Joseph! 😄

**Pull request merged**
