### PR TITLE
Explicit comms shuffle: sort workers when assigning output partitions

### PR DESCRIPTION
**Pull request by madsbk**

### CODE REVIEW

**Review by pentschev — COMMENTED** [review]
Looks fine to me, do we need a test here too @madsbk ?

**Comment by madsbk** [comment]
> Looks fine to me, do we need a test here too @madsbk ?

No, I don't think so this is only a minor performance optimization.

**Review by pentschev — APPROVED** [review]
LGTM, thanks @madsbk .

**Comment by pentschev** [comment]
@gpucibot merge

**Pull request merged**
