### PR TITLE
Do not skip DGX/TCP tests when ucp is not installed

### PR DESCRIPTION
**Pull request by pentschev**

### CODE REVIEW

**Comment by pentschev** [comment]
rerun tests

**Comment by quasiben** [comment]
This and #437 are both failing within the distributed testing framework we bring in:
https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/dask-cuda/job/prb/job/dask-cuda-gpu-test/CUDA=10.1,OS=ubuntu16.04,PYTHON=3.7/23/console

**Comment by pentschev** [comment]
I'm not sure yet whether there's something we need to update in distributed, but I found that reverting to `pytest-asyncio=0.12.0` resolves the issues locally.

**Comment by pentschev** [comment]
It seems like this only happened now because there was no `pytest-asyncio=0.14.0` in Anaconda until 3 days ago, even though it has been released months ago: https://anaconda.org/conda-forge/pytest-asyncio/files .

**Comment by quasiben** [comment]
Yes, that makes sense:
https://github.com/dask/distributed/pull/4212

**Comment by pentschev** [comment]
I hadn't seen that, thanks for the link @quasiben , I'll pin it in dask-cuda as well for now.

**Review by dillon-cullinan — APPROVED** [review]

**Review by quasiben — APPROVED** [review]
Thank you @pentschev !

**Pull request merged**
