### PR TITLE
Set RAPIDS_NO_INITIALIZE at the top of CUDAWorker/LocalCUDACluster

### PR DESCRIPTION
**Pull request by pentschev**
Fix issue with dask-cuda-worker initializing on GPU 0 only.

### CODE REVIEW

**Comment by quasiben** [comment]
@peter pointed out his problem probably happens because dask will import cuDF serialization code

**Comment by pentschev** [comment]
rerun tests

**Comment by jakirkham** [comment]
Thanks Peter! 😄

**Comment by pentschev** [comment]
Thanks for reviews everyone! 😄

**Pull request merged**
