### PR TITLE
Run dask nvml tests

### PR DESCRIPTION
**Pull request by quasiben**
Run tests from https://github.com/dask/distributed/pull/3810

### CODE REVIEW

**Comment by quasiben** [comment]
Current test failures:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - dask-cudf=0.17
  - ucx-py=0.17
  - cudf=0.17
```

Looks like a conda issue ?

**Comment by quasiben** [comment]
rerun tests

**Comment by jakirkham** [comment]
Yeah OPS is still working on creating those

**Comment by quasiben** [comment]
Temporarily targeting 0.16

**Comment by quasiben** [comment]
rerun tests

**Comment by jakirkham** [comment]
I think this still has history from `branch-0.17`, which is trying to still install `0.17` packages. Would recommend just rebasing on top of `branch-0.16` and removing any commits from `branch-0.17`. That should hopefully fix the issue.

**Review by mike-wendt — APPROVED** [review]

**Comment by quasiben** [comment]
I'll just wait until 0.17 things are fixed.  Thanks @jakirkham

**Comment by quasiben** [comment]
rerun tests

**Comment by madsbk** [comment]
rerun tests

**Comment by quasiben** [comment]
Still seeing some conda issues.  I think they should be resolved soon...

**Comment by jakirkham** [comment]
Actually I think we need this in `branch-0.16` as we consolidated the tests into `distributed/diagnostics/tests/test_nvml.py`. Though this is only a CI change, so should be safe. Would you be willing to retarget this to `branch-0.16` and rebase on top of that branch, Ben?

**Comment by jakirkham** [comment]
May need to rebase to get rid of commit ( https://github.com/rapidsai/dask-cuda/pull/408/commits/25327eb605500d4adb1fba3de1ff3180cdb074f8 ).

**Comment by quasiben** [comment]
@raydouglass I removed the doc update 0.17 commit.  We are targeting this fix for the upcoming release

**Comment by jakirkham** [comment]
For some reason the commit history shows commit some explicit comms changes. However those changes are the same ones already in `branch-0.16` as commit ( https://github.com/rapidsai/dask-cuda/commit/b6cfacc799e03379e1d24a0170b9240716727b01 ). I think we can ignore these.

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
> For some reason the commit history shows some commit with explicit comms changes. However those changes are the same ones already in `branch-0.16` as commit ( [b6cfacc](https://github.com/rapidsai/dask-cuda/commit/b6cfacc799e03379e1d24a0170b9240716727b01) ). I think we can ignore those.

Note the resulting commit ( https://github.com/rapidsai/dask-cuda/commit/93458a4d83a56ff93913b4991fe9cc9d715c01b7 ) only contains the relevant CI change as expected.

**Pull request merged**
