### PR TITLE
Remove line-break that's breaking link

### PR DESCRIPTION
**Pull request by ntabris**
https://docs.rapids.ai/api/dask-cuda/nightly/examples/best-practices.html currently shows 

> [...] don’t force and Host-to-Device/Device-to-Host transfers. See ` Accelerated Networking`_ for more discussion

rather than the link. This should fix that.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by pentschev** [comment]
ok to test

**Comment by quasiben** [comment]
add to allowlist

**Comment by quasiben** [comment]
Thanks @ntabris

**Review by pentschev — APPROVED** [review]

**Pull request merged**
