### PR TITLE
Rely on Dask's ability to serialize collections

### PR DESCRIPTION
**Pull request by jakirkham**
Follow-up to PR ( https://github.com/rapidsai/dask-cuda/pull/268 )
Requires ( https://github.com/rapidsai/dask-cuda/pull/306 )

As Dask is able to serialize collections of objects, simply serialize all of the parts together in one step.

### CODE REVIEW

**Comment by pentschev** [comment]
https://github.com/rapidsai/dask-cuda/pull/308 should fix errors.

**Comment by pentschev** [comment]
rerun tests

**Comment by jakirkham** [comment]
Thanks Peter! Looks like this is now passing 😄

**Comment by jakirkham** [comment]
Thanks Peter! 😄

**Pull request merged**
