### PR TITLE
Drop Python 3.7 handling for pickle protocol 4

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/rapidsai/dask-cuda/issues/1131

Now that Python 3.8 is the minimum supported version, drop the special casing for Python 3.7's `HIGHEST_PROTOCOL`, which was 4 (not 5). In Python 3.8+, `HIGHEST_PROTOCOL >= 5`. So none of these branches are needed any more.

### CODE REVIEW

**Comment by jakirkham** [comment]
Toggling for CI

**Review by madsbk — APPROVED** [review]
Thanks @jakirkham

**Comment by pentschev** [comment]
Failures are unrelated, tracking that in https://github.com/rapidsai/dask-cuda/issues/1134 .

**Review by pentschev — APPROVED** [review]
Seems sensible to me, thanks John!

**Comment by jakirkham** [comment]
Thanks Peter & Mads! 🙏

**Pull request merged**
