### PR TITLE
Add CPU support to CuPy transpose sum benchmark

### PR DESCRIPTION
**Pull request by pentschev**

### CODE REVIEW

**Review by quasiben — APPROVED** [review]
Thank you @pentschev !  I had meant to do this some time ago and forgot about it.

**Comment by quasiben** [comment]
Failing do to linting issues:
> dask_cuda/benchmarks/local_cupy_transpose_sum.py:92:55: F821 undefined name 'np'

**Comment by pentschev** [comment]
Thanks @quasiben , should be fixed now.

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Peter! Also thanks for reviewing Ben! 😄

**Pull request merged**
