### PR TITLE
cudf-merge-benchmark now reports throughput

### PR DESCRIPTION
**Pull request by madsbk**
Makes the benchmark report throughput.

```
$ python local_cudf_merge.py -p ucx -d 4,5,6,7 -c 100000000 --runs 3 --disable-infiniband
Merge benchmark
-------------------------------
Chunk-size  | 100000000
Frac-match  | 0.3
Ignore-size | 1.05 MB
Protocol    | ucx
Device(s)   | 4,5,6,7
rmm-pool    | True
tcp         | True
ib          | False
nvlink      | True
===============================
Wall-clock  | Throughput
-------------------------------
2.18 s      | 5.86 GB/s
1.76 s      | 7.29 GB/s
1.75 s      | 7.32 GB/s
===============================
(w1,w2)     | 25% 50% 75% (total nbytes)
-------------------------------
(04,05)     | 4.42 GB/s 4.92 GB/s 5.55 GB/s (12.00 GB)
(04,06)     | 4.34 GB/s 4.88 GB/s 5.65 GB/s (7.20 GB)
(04,07)     | 4.32 GB/s 5.17 GB/s 5.60 GB/s (7.20 GB)
(05,04)     | 3.87 GB/s 5.12 GB/s 5.69 GB/s (12.00 GB)
(05,06)     | 3.90 GB/s 5.22 GB/s 5.50 GB/s (7.20 GB)
(05,07)     | 4.37 GB/s 4.77 GB/s 5.82 GB/s (7.20 GB)
(06,04)     | 4.81 GB/s 5.31 GB/s 5.42 GB/s (7.20 GB)
(06,05)     | 4.41 GB/s 5.42 GB/s 6.12 GB/s (7.20 GB)
(06,07)     | 4.67 GB/s 5.92 GB/s 12.25 GB/s (14.40 GB)
(07,04)     | 4.71 GB/s 5.41 GB/s 6.47 GB/s (7.20 GB)
(07,05)     | 4.91 GB/s 5.38 GB/s 5.90 GB/s (7.20 GB)
(07,06)     | 5.04 GB/s 6.42 GB/s 9.50 GB/s (14.40 GB)
```

### CODE REVIEW

**Comment by quasiben** [comment]
Thanks @madsbk! do you also have time to run on a DGX2 ?

**Comment by madsbk** [comment]
#### On DGX-2 No InfiniBand
```
$ python local_cudf_merge.py -p ucx -d 4,5,6,7 -c 100000000 --runs 3 --disable-infiniband
Merge benchmark
-------------------------------
Chunk-size  | 100000000
Frac-match  | 0.3
Ignore-size | 1.05 MB
Protocol    | ucx
Device(s)   | 4,5,6,7
rmm-pool    | True
tcp         | True
ib          | False
nvlink      | True
===============================
Wall-clock  | Throughput
-------------------------------
2.51 s      | 5.10 GB/s
2.29 s      | 5.60 GB/s
2.28 s      | 5.62 GB/s
===============================
```

#### On DGX-2 No InfiniBand and IPC CACHE
```
$  UCXPY_ALLOC_CACHE=y UCX_CUDA_IPC_CACHE=y  python local_cudf_merge.py -p ucx -d 4,5,6,7 -c 100000000 --runs 3 --disable-infiniband
Merge benchmark
-------------------------------
Chunk-size  | 100000000
Frac-match  | 0.3
Ignore-size | 1.05 MB
Protocol    | ucx
Device(s)   | 4,5,6,7
rmm-pool    | True
tcp         | True
ib          | False
nvlink      | True
===============================
Wall-clock  | Throughput
-------------------------------
1.43 s      | 8.97 GB/s
1.32 s      | 9.68 GB/s
1.36 s      | 9.44 GB/s
===============================
```

@quasiben, we are still far from the performance of the pure ucxpy implementation of cudf merge.

**Comment by quasiben** [comment]
Ok, thanks!

**Comment by madsbk** [comment]
For comparison, running without Dask (rapidsai/ucx-py#378).

#### DGX2, 4 nodes with cache
```
$ UCXPY_COMM_BUFFER=y UCX_CUDA_IPC_CACHE=y UCX_TLS=tcp,cuda_copy,cuda_ipc,sockcm python  cudf-merge.py -c 100000000 --devs=0,1,2,3 --net-devices=auto
cudf merge benchmark
----------------------------
device(s)      | [0, 1, 2, 3]
chunks-per-dev | 1
rows-per-chunk | 100000000
data-processed | 12.80 GB
frac-match     | 0.3
============================
Wall-clock     | 276.80 ms
Bandwidth      | 21.35 GB/s
Throughput     | 46.24 GB/s
```

#### DGX2, 16 nodes with cache
```
UCXPY_COMM_BUFFER=y UCX_CUDA_IPC_CACHE=y UCX_TLS=tcp,cuda_copy,cuda_ipc,sockcm python cudf-merge.py -c 100000000 --devs=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 --net-devices=auto
cudf merge benchmark
----------------------------
device(s)      | [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
chunks-per-dev | 1
rows-per-chunk | 100000000
data-processed | 51.20 GB
frac-match     | 0.3
============================
Wall-clock     | 336.57 ms
Bandwidth      | 22.49 GB/s
Throughput     | 152.12 GB/s
```

**Comment by nsakharnykh** [comment]
Thanks @madsbk, adding @gaohao95 for visibility

**Pull request merged**
